spring:
  application:
    name: kooora-backend
  
  datasource:
    url: jdbc:h2:mem:koooradb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jackson:
    serialization:
      fail-on-empty-beans: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
  
  security:
    user:
      name: admin
      password: admin123

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    com.kooora: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: app.log

# Application Configuration
app:
  jwt:
    secret: ${JWT_SECRET:kooora-secret-key-2024-very-long-and-secure-key-for-production-must-be-at-least-256-bits}
    expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds
  upload:
    dir: uploads
    max-file-size: 5242880  # 5MB
  notifications:
    vapid:
      public-key: # Add your VAPID public key here (generate using web-push library)
      private-key: # Add your VAPID private key here (keep secure)
      subject: mailto:admin@kooora.com

# JWT Configuration (for backward compatibility)
jwt:
  secret: ${JWT_SECRET:kooora-secret-key-2024-very-long-and-secure-key-for-production-must-be-at-least-256-bits}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# External API Configuration
external:
  api:
    enabled: false  # Set to true to enable external API integration
    football:
      url: https://api.football-data.org/v4
      key: # Add your API key here

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
